version: 2
updates:
- package-ecosystem: "maven"
  directory: "/lemminx-schematron"
  schedule:
    interval: "weekly"
  allow:
    - dependency-name: "@types/node"
      update-types:
        - "version-update:semver-minor"
        - "version-update:semver-patch"
- package-ecosystem: "npm"
  directory: "/vscode-schematron"
  schedule:
    interval: "weekly"
  groups:
    eslint:
      patterns:
        - "@eslint/js"
        - "eslint"
