version: 2
updates:
- package-ecosystem: "maven"
  directory: "/lemminx-schematron"
  schedule:
    interval: "weekly"
- package-ecosystem: "npm"
  directory: "/vscode-schematron"
  schedule:
    interval: "weekly"
  groups:
    eslint:
      patterns:
        - "@eslint/js"
        - "eslint"
