name: Publish VS Code Extension
on: workflow_dispatch
jobs:
  Build-Extension:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64
          cache: maven
      - name: Install node deps
        working-directory: "vscode-schematron"
        run: npm ci
      - name: Install extension packaging tools
        run: npm i -g @vscode/vsce ovsx
      - name: Package extension
        working-directory: "vscode-schematron"
        run: vsce package
      - name: Publish to VS Code Marketplace
        working-directory: "vscode-schematron"
        run: 'vsce publish -p ${{ secrets.VSCE_TOKEN }} --packagePath *.vsix'
      - name: Publish to OpenVSX
        working-directory: "vscode-schematron"
        run: 'ovsx publish -p ${{ secrets.OVSX_TOKEN }} --packagePath *.vsix'
      - name: Prepare Environment Variables
        run: |
          echo "EXT_VERSION=$(cat vscode-schematron/package.json | jq -r .version)" >> $GITHUB_ENV
      - name: Publish to GH Release Tab
        uses: "marvinpinto/action-automatic-releases@919008cf3f741b179569b7a6fb4d8860689ab7f0"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ env.EXT_VERSION }}"
          draft: true
          files: |
            *.vsix
