name: Continuous Integration Testing
on:
  push:
    branches:
      - main
  pull_request: {}
jobs:
  Maven-Verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64
          cache: maven
      - name: Run the Maven verify phase
        working-directory: "lemminx-schematron"
        run: mvn --batch-mode --update-snapshots verify
  VSCode-Extension-Verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install node deps
        working-directory: "vscode-schematron"
        run: npm ci
      - name: Run VS Code extension tests
        working-directory: "vscode-schematron"
        run: xvfb-run npm test